name: Pull Request Runner

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

env:
  DOTNET_VERSIONS: |
    8.0.x
    10.0.x

jobs:
  build-flattery:
    name: Build Flattery (${{ matrix.dotnet-version }})
    strategy:
      matrix:
        dotnet-version: ['8.0.x', '10.0.x']
    uses: ./.github/workflows/build-project.yml
    with:
      CONFIGURATION: Release
      DOTNET_VERSION: ${{ matrix.dotnet-version }}
      PROJECT_PATH: './src/Flattery/Flattery.csproj'

  test-flattery:
    name: Test Flattery (${{ matrix.dotnet-version }})
    strategy:
      matrix:
        dotnet-version: ['8.0.x', '10.0.x']
    uses: ./.github/workflows/run-test-suite.yml
    with:
      CONFIGURATION: Release
      DOTNET_VERSION: ${{ matrix.dotnet-version }}
      PROJECT_PATH: './test/Flattery.Tests/Flattery.Tests.csproj'
